
package local.mglsi.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyServicesService", targetNamespace = "http://mglsi.local/soap", wsdlLocation = "http://mglsi.local/soap/wsdl")
public class MyServicesService
    extends Service
{

    private final static URL MYSERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSERVICESSERVICE_EXCEPTION;
    private final static QName MYSERVICESSERVICE_QNAME = new QName("http://mglsi.local/soap", "MyServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://mglsi.local/soap/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSERVICESSERVICE_WSDL_LOCATION = url;
        MYSERVICESSERVICE_EXCEPTION = e;
    }

    public MyServicesService() {
        super(__getWsdlLocation(), MYSERVICESSERVICE_QNAME);
    }

    public MyServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSERVICESSERVICE_QNAME, features);
    }

    public MyServicesService(URL wsdlLocation) {
        super(wsdlLocation, MYSERVICESSERVICE_QNAME);
    }

    public MyServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSERVICESSERVICE_QNAME, features);
    }

    public MyServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyServicesPort
     */
    @WebEndpoint(name = "MyServicesPort")
    public MyServicesPort getMyServicesPort() {
        return super.getPort(new QName("http://mglsi.local/soap", "MyServicesPort"), MyServicesPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyServicesPort
     */
    @WebEndpoint(name = "MyServicesPort")
    public MyServicesPort getMyServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mglsi.local/soap", "MyServicesPort"), MyServicesPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSERVICESSERVICE_EXCEPTION!= null) {
            throw MYSERVICESSERVICE_EXCEPTION;
        }
        return MYSERVICESSERVICE_WSDL_LOCATION;
    }

}
